#!/bin/bash

gource combined.txt \
    -s 0.1 \
    -1920x1080 \
    --auto-skip-seconds .1 \
    --multi-sampling \
    --stop-at-end \
    --key \
    --highlight-users \
    --date-format "%d/%m/%y" \
    --hide mouse,filenames \
    --file-idle-time 0 \
    --max-files 0  \
    --background-colour 000000 \
    --font-size 25 \
    --output-framerate 60 \
    --output-ppm-stream - \
   | ffmpeg -y -r 60 -f image2pipe -probesize 1G -vcodec ppm -i - -b:v 65536K movie.mp4
