name: Delete Class
description: Permanently delete a class
labels: ["deleteclass"]
assignees:
  - KonradHoeffner
body:
  - type: input
    id: class
    attributes:
      label: Class
    validations:
      required: true
  - type: textarea
    id: explanation
    attributes:
      label: Explanation
