name: Delete Triple
description: Permanently delete a triple (edge)
labels: ["deletetriple"]
assignees:
  - KonradHoeffner
body:
  - type: input
    id: subject
    attributes:
      label: Subject Class
    validations:
      required: true
  - type: input
    id: predicate
    attributes:
      label: Predicate
    validations:
      required: true
  - type: input
    id: object
    attributes:
      label: Object Class
    validations:
      required: true
  - type: textarea
    id: explanation
    attributes:
      label: Explanation
