#!/bin/bash
set -e
tf="template.xml"
if [ ! -e "$tf" ]
then
 echo "********* ERROR: TEMPLATE FILE $tf DOES NOT EXIST, ABORTING. ******************************************"
 exit 1
fi

if ! hash rapper 2>/dev/null; then
 echo "********* ERROR: RAPPER NOT AVAILABLE. ABORTING. See http://librdf.org/raptor/rapper.html ****************"
 exit 1
fi

SUBS=(bb ob he it)
for ((i=1; i<${#SUBS[@]}; i++))
do
 x=${SUBS[i]}
 xf="../$x.rdf"
 if [ ! -e "$xf" ]
 then
  echo "********* ERROR: INPUT FILE $xf DOES NOT EXIST, SKIPPING SUBONTOLOGY ${x} *************************"
 else
  for ((j=0; j<i; j++))
  do
   y=${SUBS[j]}
   yf="../$y.rdf"
   if [ ! -e "$yf" ]
   then
    echo "********* ERROR: INPUT FILE $yf DOES NOT EXIST, SKIPPING SUBONTOLOGY ${y} *************************"
   else
    echo "********* Linking ${xf} with ${yf} ************************************************************"
    d="$x-$y"
    mkdir -p ${d}/tmp
    xnt=`pwd`/$d/tmp/$x.nt
    ynt=`pwd`/$d/tmp/$y.nt
    rapper -i rdfxml -o turtle $xf > $xnt
    echo $xnt
    sed "s|{x}|${x}|g" template.rdf | sed "s|{y}|${y}|g" | sed "" > ${tf}/tmp/$d.xml
   fi
  done
 fi
done
exit 0

    mkdir -p ${s}/out
    echo "** Generating main triples ******************************"
    tarql ${s}/tmp/main.tarql | rapper -i turtle - http://www.snik.eu/ontology/${s}/ > ${s}/tmp/main.nt
    echo "** Generating axioms *************************************"
    sed "s|{SUB}|${s}|g" axiom.tarql.template > ${s}/tmp/axiom.tarql
    tarql ${s}/tmp/axiom.tarql | rapper -i turtle - http://www.snik.eu/ontology/${s}/  > ${s}/tmp/axiom.nt
    
    if [ -e "${s}/instance.csv" ]
    then
    echo "** Generating instances *************************************"
    sed "s|{SUB}|${s}|g" instance.tarql.template > ${s}/tmp/instance.tarql
    tarql ${s}/tmp/instance.tarql | rapper -i turtle - http://www.snik.eu/ontology/${s}/ > ${s}/tmp/instance.nt
    else
    echo "** WARNING: ${s}/instance.csv DOES NOT EXIST. SKIPPING INSTANCES. ************************************"
    fi

    if [ -e "${s}/property.csv" ]
    then
    echo "** Generating properties ***********************************"
    sed "s|{SUB}|${s}|g" property.tarql.template > ${s}/tmp/property.tarql
    tarql ${s}/tmp/property.tarql | rapper -i turtle - http://www.snik.eu/ontology/${s}/ > ${s}/tmp/property.nt
    else
    echo "** WARNING: ${s}/property.csv DOES NOT EXIST. SKIPPING PROPERTIES ************************************"
    fi
    
    echo "** Merging ***********************************x************"
    rapper -i turtle ${s}/ontology.ttl > ${s}/tmp/ontology.nt 
    cat prefix.ttl ${s}/tmp/*.nt | rapper -i turtle -o turtle - http://www.snik.eu/ontology/${s}/ > ${s}/out/all.ttl
    echo "** Testing ************************************************"
    rapper -i turtle -c ${s}/out/all.ttl
    echo "********************************************************************************************************"
   fi
done
