#!/bin/bash
set -e
tf="template.xml"
if [ ! -e "$tf" ]
then
 echo "********* ERROR: TEMPLATE FILE $tf DOES NOT EXIST, ABORTING. ******************************************"
 exit 1
fi

if ! hash limes 2>/dev/null; then
 echo "********* ERROR: LIMES NOT AVAILABLE. ABORTING. See http://aksw.org/Projects/LIMES ****************"
 exit 1
fi

if ! hash rapper 2>/dev/null; then
 echo "********* ERROR: RAPPER NOT AVAILABLE. ABORTING. See http://librdf.org/raptor/rapper.html ****************"
 exit 1
fi

SUBS=(bb ob he it ciox)
for ((i=1; i<${#SUBS[@]}; i++))
do
 x=${SUBS[i]}
 xf="../$x.rdf"
 if [ ! -e "$xf" ]
 then
  echo "********* ERROR: INPUT FILE $xf DOES NOT EXIST, SKIPPING SUBONTOLOGY ${x} *************************"
 else
  for ((j=0; j<i; j++))
  do
   y=${SUBS[j]}
   yf="../$y.rdf"
   if [ ! -e "$yf" ]
   then
    echo "********* ERROR: INPUT FILE $yf DOES NOT EXIST, SKIPPING SUBONTOLOGY ${y} *************************"
   else
    echo "********* Linking ${xf} with ${yf} ************************************************************"
    d="$x-$y"
    mkdir -p ${d}/tmp
    mkdir -p ${d}/out
    xnt=`pwd`/$d/tmp/$x.nt
    ynt=`pwd`/$d/tmp/$y.nt
    rapper -i rdfxml -o ntriples $xf > $xnt
    rapper -i rdfxml -o ntriples $yf > $ynt
    echo $xnt
    spec=$d/tmp/$d.xml
    sed "s|{x}|${x}|g" template.xml | sed "s|{y}|${y}|g" | sed "s|{xnt}|$xnt|" | sed "s|{ynt}|$ynt|" > $spec
    limes $spec
   fi
  done
 fi
done
exit 0

