name: SHACL

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  shacl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate
        uses: konradhoeffner/shacl@v1
        with:
          data: |
            meta.ttl
            bb.ttl
            bb2.ttl
            ob.ttl
          shacl: shacl.ttl
